2021-05-19 18:39:28,810:DEBUG:certbot._internal.main:certbot version: 1.15.0
2021-05-19 18:39:28,810:DEBUG:certbot._internal.main:Location of certbot entry point: /usr/local/bin/certbot
2021-05-19 18:39:28,810:DEBUG:certbot._internal.main:Arguments: ['--webroot', '--webroot-path=/usr/share/nginx/html/letsencrypt', '--email', 'robotixclub@nitrr.ac.in', '--agree-tos', '--no-eff-email', '-d', 'roborix.nitrr.ac.in']
2021-05-19 18:39:28,810:DEBUG:certbot._internal.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#manual,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2021-05-19 18:39:28,824:DEBUG:certbot._internal.log:Root logging level set at 20
2021-05-19 18:39:28,824:INFO:certbot._internal.log:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2021-05-19 18:39:28,825:DEBUG:certbot._internal.plugins.selection:Requested authenticator webroot and installer None
2021-05-19 18:39:28,829:DEBUG:certbot._internal.plugins.selection:Single candidate plugin: * webroot
Description: Place files in webroot directory
Interfaces: IAuthenticator, IPlugin
Entry point: webroot = certbot._internal.plugins.webroot:Authenticator
Initialized: <certbot._internal.plugins.webroot.Authenticator object at 0x7fb0e4bc0b20>
Prep: True
2021-05-19 18:39:28,829:DEBUG:certbot._internal.plugins.selection:Selected authenticator <certbot._internal.plugins.webroot.Authenticator object at 0x7fb0e4bc0b20> and installer None
2021-05-19 18:39:28,829:INFO:certbot._internal.plugins.selection:Plugins selected: Authenticator webroot, Installer None
2021-05-19 18:39:28,837:DEBUG:certbot._internal.main:Picked account: <Account(RegistrationResource(body=Registration(key=None, contact=(), agreement=None, status=None, terms_of_service_agreed=None, only_return_existing=None, external_account_binding=None), uri='https://acme-v02.api.letsencrypt.org/acme/acct/124178225', new_authzr_uri=None, terms_of_service=None), 4ccf1848dab134df4a9a7b01a72cbb83, Meta(creation_dt=datetime.datetime(2021, 5, 19, 18, 39, 12, tzinfo=<UTC>), creation_host='30d663a1f659', register_to_eff=None))>
2021-05-19 18:39:28,837:DEBUG:acme.client:Sending GET request to https://acme-v02.api.letsencrypt.org/directory.
2021-05-19 18:39:28,839:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): acme-v02.api.letsencrypt.org:443
2021-05-19 18:39:29,855:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "GET /directory HTTP/1.1" 200 658
2021-05-19 18:39:29,856:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Wed, 19 May 2021 18:39:29 GMT
Content-Type: application/json
Content-Length: 658
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "fjyT1ziM0SI": "https://community.letsencrypt.org/t/adding-random-entries-to-the-directory/33417",
  "keyChange": "https://acme-v02.api.letsencrypt.org/acme/key-change",
  "meta": {
    "caaIdentities": [
      "letsencrypt.org"
    ],
    "termsOfService": "https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf",
    "website": "https://letsencrypt.org"
  },
  "newAccount": "https://acme-v02.api.letsencrypt.org/acme/new-acct",
  "newNonce": "https://acme-v02.api.letsencrypt.org/acme/new-nonce",
  "newOrder": "https://acme-v02.api.letsencrypt.org/acme/new-order",
  "revokeCert": "https://acme-v02.api.letsencrypt.org/acme/revoke-cert"
}
2021-05-19 18:39:29,857:DEBUG:certbot.display.util:Notifying user: Requesting a certificate for roborix.nitrr.ac.in
2021-05-19 18:39:30,322:DEBUG:certbot.crypto_util:Generating RSA key (2048 bits): /etc/letsencrypt/keys/0003_key-certbot.pem
2021-05-19 18:39:30,324:DEBUG:certbot.crypto_util:Creating CSR: /etc/letsencrypt/csr/0003_csr-certbot.pem
2021-05-19 18:39:30,325:DEBUG:acme.client:Requesting fresh nonce
2021-05-19 18:39:30,325:DEBUG:acme.client:Sending HEAD request to https://acme-v02.api.letsencrypt.org/acme/new-nonce.
2021-05-19 18:39:30,588:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "HEAD /acme/new-nonce HTTP/1.1" 200 0
2021-05-19 18:39:30,589:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Wed, 19 May 2021 18:39:30 GMT
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: 0004ji6VoRpGFIHQKenAEugjGr6DVZ_spaJLU9hRsLbAUuo
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800


2021-05-19 18:39:30,591:DEBUG:acme.client:Storing nonce: 0004ji6VoRpGFIHQKenAEugjGr6DVZ_spaJLU9hRsLbAUuo
2021-05-19 18:39:30,591:DEBUG:acme.client:JWS payload:
b'{\n  "identifiers": [\n    {\n      "type": "dns",\n      "value": "roborix.nitrr.ac.in"\n    }\n  ]\n}'
2021-05-19 18:39:30,593:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/new-order:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvMTI0MTc4MjI1IiwgIm5vbmNlIjogIjAwMDRqaTZWb1JwR0ZJSFFLZW5BRXVnakdyNkRWWl9zcGFKTFU5aFJzTGJBVXVvIiwgInVybCI6ICJodHRwczovL2FjbWUtdjAyLmFwaS5sZXRzZW5jcnlwdC5vcmcvYWNtZS9uZXctb3JkZXIifQ",
  "signature": "VamzkP69q3xwBx2mbkc2lFceyHe-2AomH8ye9WPSadCAzbshNfbk2fPqHUMYaIicDb9ilo5QiiGUDaDxmgBvmJtgtQF9PDOCXkrLwyMc2aIG1L6rGBIqLoPqAK77yrQS9bhvPXy_fwNquVk9wMTQBLcxqdXPpIYY0Jyxv1KWadYiUhKZ23Z_Qmi7DL5KEY9MXhBj-VMUjQdI3zC5-1JXlloFZzySsX_-8D30NRwPm-_aTAZDkuPjG_UmSda8S85L8phsxe-xtDrNZqAMG3MO5ZyP6oyTmF1TMYU3OxdfNGtnN41HD3hGPpM4SWE9F_Eal1DX7YqAv_6ZlnRTgWUP1g",
  "payload": "ewogICJpZGVudGlmaWVycyI6IFsKICAgIHsKICAgICAgInR5cGUiOiAiZG5zIiwKICAgICAgInZhbHVlIjogInJvYm9yaXgubml0cnIuYWMuaW4iCiAgICB9CiAgXQp9"
}
2021-05-19 18:39:31,016:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/new-order HTTP/1.1" 201 341
2021-05-19 18:39:31,016:DEBUG:acme.client:Received response:
HTTP 201
Server: nginx
Date: Wed, 19 May 2021 18:39:30 GMT
Content-Type: application/json
Content-Length: 341
Connection: keep-alive
Boulder-Requester: 124178225
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Location: https://acme-v02.api.letsencrypt.org/acme/order/124178225/9812498129
Replay-Nonce: 0003rxN0sEl0l7AmR18vIfh2BajCAsPAyTilrfjnwrizlks
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "status": "pending",
  "expires": "2021-05-26T18:39:30Z",
  "identifiers": [
    {
      "type": "dns",
      "value": "roborix.nitrr.ac.in"
    }
  ],
  "authorizations": [
    "https://acme-v02.api.letsencrypt.org/acme/authz-v3/13264627897"
  ],
  "finalize": "https://acme-v02.api.letsencrypt.org/acme/finalize/124178225/9812498129"
}
2021-05-19 18:39:31,017:DEBUG:acme.client:Storing nonce: 0003rxN0sEl0l7AmR18vIfh2BajCAsPAyTilrfjnwrizlks
2021-05-19 18:39:31,017:DEBUG:acme.client:JWS payload:
b''
2021-05-19 18:39:31,018:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/authz-v3/13264627897:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvMTI0MTc4MjI1IiwgIm5vbmNlIjogIjAwMDNyeE4wc0VsMGw3QW1SMTh2SWZoMkJhakNBc1BBeVRpbHJmam53cml6bGtzIiwgInVybCI6ICJodHRwczovL2FjbWUtdjAyLmFwaS5sZXRzZW5jcnlwdC5vcmcvYWNtZS9hdXRoei12My8xMzI2NDYyNzg5NyJ9",
  "signature": "RZd0R--GeZ1HTEju9AyQu39WPODxrC5H_h45L9MUru2O0c4i3iZMg0bu49IbH2NOWrNftOxLzzAnAezqoMzdBpPS-E4cbWGW3o4e9UPpEhD1cyOJl56Tg1qOTEfRoMo7X0VoWZ-zyuucr157Thcf5gUtNuOVTuljJGYIXQCDJ7HCbGhSllv3CpwRearAhG8HKDBa_q2pk7JBOkQebHz1V5ZtCFELe-sFD1Yqh8-WD6YTTrfTosrY0lm1lDYdi3OJSjPLp8DOELSCX_4JMs-XCjaweHNjEKOG1B8juQom_f47a6MP_pEuQh-8Ebfs-Uve54ch7G6_0yLItXDmCtKy3A",
  "payload": ""
}
2021-05-19 18:39:31,298:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/authz-v3/13264627897 HTTP/1.1" 200 800
2021-05-19 18:39:31,299:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Wed, 19 May 2021 18:39:31 GMT
Content-Type: application/json
Content-Length: 800
Connection: keep-alive
Boulder-Requester: 124178225
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: 0003D_-VC_2qeF-0sqfbxa78-1_Q583Xt20xTtWHWjQFgCQ
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "identifier": {
    "type": "dns",
    "value": "roborix.nitrr.ac.in"
  },
  "status": "pending",
  "expires": "2021-05-26T18:39:30Z",
  "challenges": [
    {
      "type": "http-01",
      "status": "pending",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/13264627897/TZIxmA",
      "token": "mWYnQrBTWFWKA9pfob_9AhpBSmnIe7jxEA8gCAcHoAA"
    },
    {
      "type": "dns-01",
      "status": "pending",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/13264627897/B32JCQ",
      "token": "mWYnQrBTWFWKA9pfob_9AhpBSmnIe7jxEA8gCAcHoAA"
    },
    {
      "type": "tls-alpn-01",
      "status": "pending",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/13264627897/hA4AJA",
      "token": "mWYnQrBTWFWKA9pfob_9AhpBSmnIe7jxEA8gCAcHoAA"
    }
  ]
}
2021-05-19 18:39:31,299:DEBUG:acme.client:Storing nonce: 0003D_-VC_2qeF-0sqfbxa78-1_Q583Xt20xTtWHWjQFgCQ
2021-05-19 18:39:31,300:INFO:certbot._internal.auth_handler:Performing the following challenges:
2021-05-19 18:39:31,300:INFO:certbot._internal.auth_handler:http-01 challenge for roborix.nitrr.ac.in
2021-05-19 18:39:31,301:INFO:certbot._internal.plugins.webroot:Using the webroot path /usr/share/nginx/html/letsencrypt for all unmatched domains.
2021-05-19 18:39:31,302:DEBUG:certbot._internal.plugins.webroot:Creating root challenges validation dir at /usr/share/nginx/html/letsencrypt/.well-known/acme-challenge
2021-05-19 18:39:31,303:DEBUG:certbot._internal.plugins.webroot:Attempting to save validation to /usr/share/nginx/html/letsencrypt/.well-known/acme-challenge/mWYnQrBTWFWKA9pfob_9AhpBSmnIe7jxEA8gCAcHoAA
2021-05-19 18:39:31,303:INFO:certbot._internal.auth_handler:Waiting for verification...
2021-05-19 18:39:31,304:DEBUG:acme.client:JWS payload:
b'{}'
2021-05-19 18:39:31,305:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/chall-v3/13264627897/TZIxmA:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvMTI0MTc4MjI1IiwgIm5vbmNlIjogIjAwMDNEXy1WQ18ycWVGLTBzcWZieGE3OC0xX1E1ODNYdDIweFR0V0hXalFGZ0NRIiwgInVybCI6ICJodHRwczovL2FjbWUtdjAyLmFwaS5sZXRzZW5jcnlwdC5vcmcvYWNtZS9jaGFsbC12My8xMzI2NDYyNzg5Ny9UWkl4bUEifQ",
  "signature": "KRT9bn_Ek8vKUYbK5OPfnhFwOdmyzBKAuIJmZJ2OUEwbODGxQ46IEOmCbG-8W3dg87YehlicYKnz-N4x2Ah_wvyFcD-TyBTpbVjTFAZFq5a2h98o9-6gZ0xqSmuovLuyC4jQzRfqfys0oFwmvieSJPX_UaqmYkNfG6dydpVhrb7Z-9nD2z9yoLYj5LwmfBXGGijmoTEwwidfRFheqVZBaJX5LUK-62VL-QQ98eTueJFFO-Uz--ulYJK6rwBFGHYuH7MjhWv9EI_HH5ojhBO4Q1uRaDF4naoSZuPQdLa2MMYAyTiYqYFgq9DpFhr6DRlwGvHGyDYzgOb87ejYE8ySIQ",
  "payload": "e30"
}
2021-05-19 18:39:31,598:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/chall-v3/13264627897/TZIxmA HTTP/1.1" 200 186
2021-05-19 18:39:31,599:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Wed, 19 May 2021 18:39:31 GMT
Content-Type: application/json
Content-Length: 186
Connection: keep-alive
Boulder-Requester: 124178225
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index", <https://acme-v02.api.letsencrypt.org/acme/authz-v3/13264627897>;rel="up"
Location: https://acme-v02.api.letsencrypt.org/acme/chall-v3/13264627897/TZIxmA
Replay-Nonce: 0003iPSHnlCYl8nnvmK_VmlFumrwDfdMuA1rhQ3EA11IE14
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "type": "http-01",
  "status": "pending",
  "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/13264627897/TZIxmA",
  "token": "mWYnQrBTWFWKA9pfob_9AhpBSmnIe7jxEA8gCAcHoAA"
}
2021-05-19 18:39:31,599:DEBUG:acme.client:Storing nonce: 0003iPSHnlCYl8nnvmK_VmlFumrwDfdMuA1rhQ3EA11IE14
2021-05-19 18:39:32,601:DEBUG:acme.client:JWS payload:
b''
2021-05-19 18:39:32,602:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/authz-v3/13264627897:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvMTI0MTc4MjI1IiwgIm5vbmNlIjogIjAwMDNpUFNIbmxDWWw4bm52bUtfVm1sRnVtcndEZmRNdUExcmhRM0VBMTFJRTE0IiwgInVybCI6ICJodHRwczovL2FjbWUtdjAyLmFwaS5sZXRzZW5jcnlwdC5vcmcvYWNtZS9hdXRoei12My8xMzI2NDYyNzg5NyJ9",
  "signature": "nPboEvrCimB1qFoulBagKiYWuzFGAIXmJUjkXYdhFXA6OsHregXPaKfO0F4sgPUbUWHb3APBOlzEYvTcN5ZPAqVOsvGvYirmu7uVFWUXJQUAAXg5hE12BIskboQ9Rf33UbnjBaekBz3XucgZsjY6kyeUOOeVL0Oa8TSt7685POfVWKgElhGxWKBqBicLzkukoufz6DwemKvyvfVNbhGRa5mCAq2xCpiywDWc53kbnBmituOxwI5wY4GXIHk1Ny9bALv-RJbXzPHpz15UuTIiixlG8-GUFJ2am1Lh4ihXuTOdHeVPEKTyxusilWvSfmEbU1u6kcs2jF35QPt3LTJXvA",
  "payload": ""
}
2021-05-19 18:39:32,884:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/authz-v3/13264627897 HTTP/1.1" 200 643
2021-05-19 18:39:32,884:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Wed, 19 May 2021 18:39:32 GMT
Content-Type: application/json
Content-Length: 643
Connection: keep-alive
Boulder-Requester: 124178225
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: 0003EeiMG7iyAIB3zs732LONkVO3E8ULY-1f3fLnQgsnJyc
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "identifier": {
    "type": "dns",
    "value": "roborix.nitrr.ac.in"
  },
  "status": "invalid",
  "expires": "2021-05-26T18:39:30Z",
  "challenges": [
    {
      "type": "http-01",
      "status": "invalid",
      "error": {
        "type": "urn:ietf:params:acme:error:dns",
        "detail": "DNS problem: NXDOMAIN looking up A for roborix.nitrr.ac.in - check that a DNS record exists for this domain",
        "status": 400
      },
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/13264627897/TZIxmA",
      "token": "mWYnQrBTWFWKA9pfob_9AhpBSmnIe7jxEA8gCAcHoAA",
      "validated": "2021-05-19T18:39:31Z"
    }
  ]
}
2021-05-19 18:39:32,884:DEBUG:acme.client:Storing nonce: 0003EeiMG7iyAIB3zs732LONkVO3E8ULY-1f3fLnQgsnJyc
2021-05-19 18:39:32,885:WARNING:certbot._internal.auth_handler:Challenge failed for domain roborix.nitrr.ac.in
2021-05-19 18:39:32,886:INFO:certbot._internal.auth_handler:http-01 challenge for roborix.nitrr.ac.in
2021-05-19 18:39:32,886:DEBUG:certbot._internal.reporter:Reporting to user: The following errors were reported by the server:

Domain: roborix.nitrr.ac.in
Type:   dns
Detail: DNS problem: NXDOMAIN looking up A for roborix.nitrr.ac.in - check that a DNS record exists for this domain
2021-05-19 18:39:32,887:DEBUG:certbot._internal.error_handler:Encountered exception:
Traceback (most recent call last):
  File "/opt/certbot/src/certbot/certbot/_internal/auth_handler.py", line 91, in handle_authorizations
    self._poll_authorizations(authzrs, max_retries, best_effort)
  File "/opt/certbot/src/certbot/certbot/_internal/auth_handler.py", line 179, in _poll_authorizations
    raise errors.AuthorizationError('Some challenges have failed.')
certbot.errors.AuthorizationError: Some challenges have failed.

2021-05-19 18:39:32,887:DEBUG:certbot._internal.error_handler:Calling registered functions
2021-05-19 18:39:32,887:INFO:certbot._internal.auth_handler:Cleaning up challenges
2021-05-19 18:39:32,887:DEBUG:certbot._internal.plugins.webroot:Removing /usr/share/nginx/html/letsencrypt/.well-known/acme-challenge/mWYnQrBTWFWKA9pfob_9AhpBSmnIe7jxEA8gCAcHoAA
2021-05-19 18:39:32,887:DEBUG:certbot._internal.plugins.webroot:All challenges cleaned up
2021-05-19 18:39:32,888:DEBUG:certbot._internal.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/local/bin/certbot", line 33, in <module>
    sys.exit(load_entry_point('certbot', 'console_scripts', 'certbot')())
  File "/opt/certbot/src/certbot/certbot/main.py", line 15, in main
    return internal_main.main(cli_args)
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 1435, in main
    return config.func(config, plugins)
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 1304, in certonly
    lineage = _get_and_save_cert(le_client, config, domains, certname, lineage)
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 140, in _get_and_save_cert
    lineage = le_client.obtain_and_enroll_certificate(domains, certname)
  File "/opt/certbot/src/certbot/certbot/_internal/client.py", line 444, in obtain_and_enroll_certificate
    cert, chain, key, _ = self.obtain_certificate(domains)
  File "/opt/certbot/src/certbot/certbot/_internal/client.py", line 374, in obtain_certificate
    orderr = self._get_order_and_authorizations(csr.data, self.config.allow_subset_of_names)
  File "/opt/certbot/src/certbot/certbot/_internal/client.py", line 424, in _get_order_and_authorizations
    authzr = self.auth_handler.handle_authorizations(orderr, best_effort)
  File "/opt/certbot/src/certbot/certbot/_internal/auth_handler.py", line 91, in handle_authorizations
    self._poll_authorizations(authzrs, max_retries, best_effort)
  File "/opt/certbot/src/certbot/certbot/_internal/auth_handler.py", line 179, in _poll_authorizations
    raise errors.AuthorizationError('Some challenges have failed.')
certbot.errors.AuthorizationError: Some challenges have failed.
2021-05-19 18:39:32,889:ERROR:certbot._internal.log:Some challenges have failed.
