2021-05-19 18:39:23,921:DEBUG:certbot._internal.main:certbot version: 1.15.0
2021-05-19 18:39:23,922:DEBUG:certbot._internal.main:Location of certbot entry point: /usr/local/bin/certbot
2021-05-19 18:39:23,922:DEBUG:certbot._internal.main:Arguments: ['--webroot', '--webroot-path=/usr/share/nginx/html/letsencrypt', '--email', 'robotixclub@nitrr.ac.in', '--agree-tos', '--no-eff-email', '-d', 'roborix.nitrr.ac.in']
2021-05-19 18:39:23,922:DEBUG:certbot._internal.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#manual,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2021-05-19 18:39:23,937:DEBUG:certbot._internal.log:Root logging level set at 20
2021-05-19 18:39:23,938:INFO:certbot._internal.log:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2021-05-19 18:39:23,939:DEBUG:certbot._internal.plugins.selection:Requested authenticator webroot and installer None
2021-05-19 18:39:23,943:DEBUG:certbot._internal.plugins.selection:Single candidate plugin: * webroot
Description: Place files in webroot directory
Interfaces: IAuthenticator, IPlugin
Entry point: webroot = certbot._internal.plugins.webroot:Authenticator
Initialized: <certbot._internal.plugins.webroot.Authenticator object at 0x7f0a6a1d0b50>
Prep: True
2021-05-19 18:39:23,943:DEBUG:certbot._internal.plugins.selection:Selected authenticator <certbot._internal.plugins.webroot.Authenticator object at 0x7f0a6a1d0b50> and installer None
2021-05-19 18:39:23,943:INFO:certbot._internal.plugins.selection:Plugins selected: Authenticator webroot, Installer None
2021-05-19 18:39:23,954:DEBUG:certbot._internal.main:Picked account: <Account(RegistrationResource(body=Registration(key=None, contact=(), agreement=None, status=None, terms_of_service_agreed=None, only_return_existing=None, external_account_binding=None), uri='https://acme-v02.api.letsencrypt.org/acme/acct/124178225', new_authzr_uri=None, terms_of_service=None), 4ccf1848dab134df4a9a7b01a72cbb83, Meta(creation_dt=datetime.datetime(2021, 5, 19, 18, 39, 12, tzinfo=<UTC>), creation_host='30d663a1f659', register_to_eff=None))>
2021-05-19 18:39:23,955:DEBUG:acme.client:Sending GET request to https://acme-v02.api.letsencrypt.org/directory.
2021-05-19 18:39:23,957:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): acme-v02.api.letsencrypt.org:443
2021-05-19 18:39:24,913:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "GET /directory HTTP/1.1" 200 658
2021-05-19 18:39:24,914:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Wed, 19 May 2021 18:39:24 GMT
Content-Type: application/json
Content-Length: 658
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "51R6YLIwXf0": "https://community.letsencrypt.org/t/adding-random-entries-to-the-directory/33417",
  "keyChange": "https://acme-v02.api.letsencrypt.org/acme/key-change",
  "meta": {
    "caaIdentities": [
      "letsencrypt.org"
    ],
    "termsOfService": "https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf",
    "website": "https://letsencrypt.org"
  },
  "newAccount": "https://acme-v02.api.letsencrypt.org/acme/new-acct",
  "newNonce": "https://acme-v02.api.letsencrypt.org/acme/new-nonce",
  "newOrder": "https://acme-v02.api.letsencrypt.org/acme/new-order",
  "revokeCert": "https://acme-v02.api.letsencrypt.org/acme/revoke-cert"
}
2021-05-19 18:39:24,915:DEBUG:certbot.display.util:Notifying user: Requesting a certificate for roborix.nitrr.ac.in
2021-05-19 18:39:25,079:DEBUG:certbot.crypto_util:Generating RSA key (2048 bits): /etc/letsencrypt/keys/0002_key-certbot.pem
2021-05-19 18:39:25,082:DEBUG:certbot.crypto_util:Creating CSR: /etc/letsencrypt/csr/0002_csr-certbot.pem
2021-05-19 18:39:25,082:DEBUG:acme.client:Requesting fresh nonce
2021-05-19 18:39:25,083:DEBUG:acme.client:Sending HEAD request to https://acme-v02.api.letsencrypt.org/acme/new-nonce.
2021-05-19 18:39:25,322:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "HEAD /acme/new-nonce HTTP/1.1" 200 0
2021-05-19 18:39:25,322:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Wed, 19 May 2021 18:39:25 GMT
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: 0103BVp_jKLrRJ2gWt40iV-Jn25AMnVxsonUYyoaN5JIdnQ
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800


2021-05-19 18:39:25,322:DEBUG:acme.client:Storing nonce: 0103BVp_jKLrRJ2gWt40iV-Jn25AMnVxsonUYyoaN5JIdnQ
2021-05-19 18:39:25,322:DEBUG:acme.client:JWS payload:
b'{\n  "identifiers": [\n    {\n      "type": "dns",\n      "value": "roborix.nitrr.ac.in"\n    }\n  ]\n}'
2021-05-19 18:39:25,324:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/new-order:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvMTI0MTc4MjI1IiwgIm5vbmNlIjogIjAxMDNCVnBfaktMclJKMmdXdDQwaVYtSm4yNUFNblZ4c29uVVl5b2FONUpJZG5RIiwgInVybCI6ICJodHRwczovL2FjbWUtdjAyLmFwaS5sZXRzZW5jcnlwdC5vcmcvYWNtZS9uZXctb3JkZXIifQ",
  "signature": "Jg8phCbj5Adzqc0QzCPcaM6hmFVHhuw0t_RDpMIwSHUumcXMfxyR5_HekKuwAF8ux4mxF2iTmAT-YkjywFYrvNd1ziQx0q_L0aZSDN_Frwqf1LT9xhMo9rsmj05KqolghUt4hJdsBgRHVjuoXWuUYHCIDU7cdqJGHyN3wc0ZbiP6JEy95eqPy5qEBKOvJGUXeM52LWykJpCuPS1R5RzrQ7ke_hPk2DN2tauBWuskAmYX5NYIWOphKec0RaXz8uswAPzAAlxLohPpGxEiwB-c9llpGcwClZxadLQ0q6tL1u3yCxjbZgnGToP-c_QMZtgUdgVrrf7QI12j5IQYH_TTVA",
  "payload": "ewogICJpZGVudGlmaWVycyI6IFsKICAgIHsKICAgICAgInR5cGUiOiAiZG5zIiwKICAgICAgInZhbHVlIjogInJvYm9yaXgubml0cnIuYWMuaW4iCiAgICB9CiAgXQp9"
}
2021-05-19 18:39:25,585:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/new-order HTTP/1.1" 201 341
2021-05-19 18:39:25,585:DEBUG:acme.client:Received response:
HTTP 201
Server: nginx
Date: Wed, 19 May 2021 18:39:25 GMT
Content-Type: application/json
Content-Length: 341
Connection: keep-alive
Boulder-Requester: 124178225
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Location: https://acme-v02.api.letsencrypt.org/acme/order/124178225/9812496974
Replay-Nonce: 0103ReavkHd2uua_ceQbuO8X2ZoQg4dxNAMTlmEwedff0s0
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "status": "pending",
  "expires": "2021-05-26T18:39:25Z",
  "identifiers": [
    {
      "type": "dns",
      "value": "roborix.nitrr.ac.in"
    }
  ],
  "authorizations": [
    "https://acme-v02.api.letsencrypt.org/acme/authz-v3/13264626496"
  ],
  "finalize": "https://acme-v02.api.letsencrypt.org/acme/finalize/124178225/9812496974"
}
2021-05-19 18:39:25,586:DEBUG:acme.client:Storing nonce: 0103ReavkHd2uua_ceQbuO8X2ZoQg4dxNAMTlmEwedff0s0
2021-05-19 18:39:25,586:DEBUG:acme.client:JWS payload:
b''
2021-05-19 18:39:25,587:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/authz-v3/13264626496:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvMTI0MTc4MjI1IiwgIm5vbmNlIjogIjAxMDNSZWF2a0hkMnV1YV9jZVFidU84WDJab1FnNGR4TkFNVGxtRXdlZGZmMHMwIiwgInVybCI6ICJodHRwczovL2FjbWUtdjAyLmFwaS5sZXRzZW5jcnlwdC5vcmcvYWNtZS9hdXRoei12My8xMzI2NDYyNjQ5NiJ9",
  "signature": "CEI-HpHeyCWraSDkbF7h84nh0aVUGGpO0fsvlZ2vHWuBQ8SR_3d_chfngjkGZz0I4ns1I65VVW1zdg4IEPAkiharZ4gj-HMdE_dcBIZMd7khsb6IbbJY46Z_9uiO0BOl6auS6-dGTORWgmBArwy6VQwDOghPfFdv15EPDgXv_FoxuI2MEDBRdeC-27PkERco_U27Y02wf_OXTs_eTe2eNFtFCQ6eHp_b7XEk-R26eT7j8JbzCXJCsBcJy-3IvZJTexcvM62uDZB15Qd3uzyVwUuSwnO-ojyFCTUXUX3YVSFYqMcmEGERf08wAJNanUo55tjDgXGO9fWymY39nMy06g",
  "payload": ""
}
2021-05-19 18:39:25,829:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/authz-v3/13264626496 HTTP/1.1" 200 800
2021-05-19 18:39:25,830:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Wed, 19 May 2021 18:39:25 GMT
Content-Type: application/json
Content-Length: 800
Connection: keep-alive
Boulder-Requester: 124178225
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: 0103xdE7I2_JTDDFoHsj69ytwVFLHALmuKfvyjeELFF4BhM
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "identifier": {
    "type": "dns",
    "value": "roborix.nitrr.ac.in"
  },
  "status": "pending",
  "expires": "2021-05-26T18:39:25Z",
  "challenges": [
    {
      "type": "http-01",
      "status": "pending",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/13264626496/_PwUng",
      "token": "QHDXuUEvDrZbgVXYc_LYbrtkmReAqY5x3lNSSlsV8eM"
    },
    {
      "type": "dns-01",
      "status": "pending",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/13264626496/oZPMwA",
      "token": "QHDXuUEvDrZbgVXYc_LYbrtkmReAqY5x3lNSSlsV8eM"
    },
    {
      "type": "tls-alpn-01",
      "status": "pending",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/13264626496/bXXGeQ",
      "token": "QHDXuUEvDrZbgVXYc_LYbrtkmReAqY5x3lNSSlsV8eM"
    }
  ]
}
2021-05-19 18:39:25,830:DEBUG:acme.client:Storing nonce: 0103xdE7I2_JTDDFoHsj69ytwVFLHALmuKfvyjeELFF4BhM
2021-05-19 18:39:25,830:INFO:certbot._internal.auth_handler:Performing the following challenges:
2021-05-19 18:39:25,831:INFO:certbot._internal.auth_handler:http-01 challenge for roborix.nitrr.ac.in
2021-05-19 18:39:25,832:INFO:certbot._internal.plugins.webroot:Using the webroot path /usr/share/nginx/html/letsencrypt for all unmatched domains.
2021-05-19 18:39:25,832:DEBUG:certbot._internal.plugins.webroot:Creating root challenges validation dir at /usr/share/nginx/html/letsencrypt/.well-known/acme-challenge
2021-05-19 18:39:25,834:DEBUG:certbot._internal.plugins.webroot:Attempting to save validation to /usr/share/nginx/html/letsencrypt/.well-known/acme-challenge/QHDXuUEvDrZbgVXYc_LYbrtkmReAqY5x3lNSSlsV8eM
2021-05-19 18:39:25,834:INFO:certbot._internal.auth_handler:Waiting for verification...
2021-05-19 18:39:25,835:DEBUG:acme.client:JWS payload:
b'{}'
2021-05-19 18:39:25,836:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/chall-v3/13264626496/_PwUng:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvMTI0MTc4MjI1IiwgIm5vbmNlIjogIjAxMDN4ZEU3STJfSlREREZvSHNqNjl5dHdWRkxIQUxtdUtmdnlqZUVMRkY0QmhNIiwgInVybCI6ICJodHRwczovL2FjbWUtdjAyLmFwaS5sZXRzZW5jcnlwdC5vcmcvYWNtZS9jaGFsbC12My8xMzI2NDYyNjQ5Ni9fUHdVbmcifQ",
  "signature": "Yv2QgegnYJZKgbSbvNEKljsETfw5N05gbRba0psIYjwLCwVGrNwjeSX_5PgGkJFDCuw0UGpQI3ptDbwhG2dBAuddeJqMfFqp0yi17ysraUWXLsqHIvoHma5cCG9FvW57DNxomeeIByq7ZUjgaUY9Rk73HnV8-E-70QUVMoRelcdGmzX0n2ZRcwuC8RQ8d_fh3ykKBiVBKGoe836eBUowJU3L72PJWWzYYQ72JThxMCEf0roQOLrxw-bQ6jnGIhFBofbD2GDk_HnVz_H_DE4iV5-GLqKBli3D2JiKdrAxzpKxtAHUO-HNSZPPOIBNbYvV_rKaDPxqwSawSfoRIedS2g",
  "payload": "e30"
}
2021-05-19 18:39:26,083:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/chall-v3/13264626496/_PwUng HTTP/1.1" 200 186
2021-05-19 18:39:26,083:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Wed, 19 May 2021 18:39:25 GMT
Content-Type: application/json
Content-Length: 186
Connection: keep-alive
Boulder-Requester: 124178225
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index", <https://acme-v02.api.letsencrypt.org/acme/authz-v3/13264626496>;rel="up"
Location: https://acme-v02.api.letsencrypt.org/acme/chall-v3/13264626496/_PwUng
Replay-Nonce: 0103NBQnUxZkUXfKuF7Ds-QUDj1xwQH6cQZeLKAm2N5t0oA
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "type": "http-01",
  "status": "pending",
  "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/13264626496/_PwUng",
  "token": "QHDXuUEvDrZbgVXYc_LYbrtkmReAqY5x3lNSSlsV8eM"
}
2021-05-19 18:39:26,083:DEBUG:acme.client:Storing nonce: 0103NBQnUxZkUXfKuF7Ds-QUDj1xwQH6cQZeLKAm2N5t0oA
2021-05-19 18:39:27,085:DEBUG:acme.client:JWS payload:
b''
2021-05-19 18:39:27,087:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/authz-v3/13264626496:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvMTI0MTc4MjI1IiwgIm5vbmNlIjogIjAxMDNOQlFuVXhaa1VYZkt1RjdEcy1RVURqMXh3UUg2Y1FaZUxLQW0yTjV0MG9BIiwgInVybCI6ICJodHRwczovL2FjbWUtdjAyLmFwaS5sZXRzZW5jcnlwdC5vcmcvYWNtZS9hdXRoei12My8xMzI2NDYyNjQ5NiJ9",
  "signature": "JWBCgX6JxsNV6twvDLQt9nIRLTu_mNH59u2IIanQ3mfest97zwO1D9RQWuQztdWiuOXkFOabpzEV5LmHEm_u5MTwJ9hok3ERjyFGPo-VZTYTDdDuhoqQrmG6FUALc2dbQqHDgWl8_FS72vakhtGDtvXlo9u79IZJITXDoi5otW2Rof8rUEHwTaF_Ak8VBtlCkmf-j_2PY7E7Vu5qqVx5C9x2SvZuFSGCXXB1aeUUgdrdZFv0uzpDJALgHZEiEQXsbsbjOcZ3ZzQ7X1rVu734pwid4cq1wf2II0IuWEzm7OvS4vNVEi1N30ag5xHryKmUU6gc_fijPHj_XQcHdIoexw",
  "payload": ""
}
2021-05-19 18:39:27,329:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/authz-v3/13264626496 HTTP/1.1" 200 643
2021-05-19 18:39:27,330:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Wed, 19 May 2021 18:39:27 GMT
Content-Type: application/json
Content-Length: 643
Connection: keep-alive
Boulder-Requester: 124178225
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: 0104NlMYE9AgGbEqa-Cs-uIc3Adw2VAo08Y8sTghoDuA3D8
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "identifier": {
    "type": "dns",
    "value": "roborix.nitrr.ac.in"
  },
  "status": "invalid",
  "expires": "2021-05-26T18:39:25Z",
  "challenges": [
    {
      "type": "http-01",
      "status": "invalid",
      "error": {
        "type": "urn:ietf:params:acme:error:dns",
        "detail": "DNS problem: NXDOMAIN looking up A for roborix.nitrr.ac.in - check that a DNS record exists for this domain",
        "status": 400
      },
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/13264626496/_PwUng",
      "token": "QHDXuUEvDrZbgVXYc_LYbrtkmReAqY5x3lNSSlsV8eM",
      "validated": "2021-05-19T18:39:25Z"
    }
  ]
}
2021-05-19 18:39:27,330:DEBUG:acme.client:Storing nonce: 0104NlMYE9AgGbEqa-Cs-uIc3Adw2VAo08Y8sTghoDuA3D8
2021-05-19 18:39:27,330:WARNING:certbot._internal.auth_handler:Challenge failed for domain roborix.nitrr.ac.in
2021-05-19 18:39:27,331:INFO:certbot._internal.auth_handler:http-01 challenge for roborix.nitrr.ac.in
2021-05-19 18:39:27,331:DEBUG:certbot._internal.reporter:Reporting to user: The following errors were reported by the server:

Domain: roborix.nitrr.ac.in
Type:   dns
Detail: DNS problem: NXDOMAIN looking up A for roborix.nitrr.ac.in - check that a DNS record exists for this domain
2021-05-19 18:39:27,332:DEBUG:certbot._internal.error_handler:Encountered exception:
Traceback (most recent call last):
  File "/opt/certbot/src/certbot/certbot/_internal/auth_handler.py", line 91, in handle_authorizations
    self._poll_authorizations(authzrs, max_retries, best_effort)
  File "/opt/certbot/src/certbot/certbot/_internal/auth_handler.py", line 179, in _poll_authorizations
    raise errors.AuthorizationError('Some challenges have failed.')
certbot.errors.AuthorizationError: Some challenges have failed.

2021-05-19 18:39:27,333:DEBUG:certbot._internal.error_handler:Calling registered functions
2021-05-19 18:39:27,333:INFO:certbot._internal.auth_handler:Cleaning up challenges
2021-05-19 18:39:27,333:DEBUG:certbot._internal.plugins.webroot:Removing /usr/share/nginx/html/letsencrypt/.well-known/acme-challenge/QHDXuUEvDrZbgVXYc_LYbrtkmReAqY5x3lNSSlsV8eM
2021-05-19 18:39:27,333:DEBUG:certbot._internal.plugins.webroot:All challenges cleaned up
2021-05-19 18:39:27,334:DEBUG:certbot._internal.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/local/bin/certbot", line 33, in <module>
    sys.exit(load_entry_point('certbot', 'console_scripts', 'certbot')())
  File "/opt/certbot/src/certbot/certbot/main.py", line 15, in main
    return internal_main.main(cli_args)
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 1435, in main
    return config.func(config, plugins)
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 1304, in certonly
    lineage = _get_and_save_cert(le_client, config, domains, certname, lineage)
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 140, in _get_and_save_cert
    lineage = le_client.obtain_and_enroll_certificate(domains, certname)
  File "/opt/certbot/src/certbot/certbot/_internal/client.py", line 444, in obtain_and_enroll_certificate
    cert, chain, key, _ = self.obtain_certificate(domains)
  File "/opt/certbot/src/certbot/certbot/_internal/client.py", line 374, in obtain_certificate
    orderr = self._get_order_and_authorizations(csr.data, self.config.allow_subset_of_names)
  File "/opt/certbot/src/certbot/certbot/_internal/client.py", line 424, in _get_order_and_authorizations
    authzr = self.auth_handler.handle_authorizations(orderr, best_effort)
  File "/opt/certbot/src/certbot/certbot/_internal/auth_handler.py", line 91, in handle_authorizations
    self._poll_authorizations(authzrs, max_retries, best_effort)
  File "/opt/certbot/src/certbot/certbot/_internal/auth_handler.py", line 179, in _poll_authorizations
    raise errors.AuthorizationError('Some challenges have failed.')
certbot.errors.AuthorizationError: Some challenges have failed.
2021-05-19 18:39:27,336:ERROR:certbot._internal.log:Some challenges have failed.
